version: '2'
services:
  # Backend service
  backend:
    name: hatchling-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://hatchling-frontend.onrender.com,https://myhatchling.ai
      - key: USERS_FILE
        value: /data/users.json
      - key: DATA_DIR
        value: /data
      - key: FLASK_ENV
        value: production
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

  # Frontend service
  frontend:
    name: hatchling-frontend
    env: node
    buildCommand: |
      cd frontend
      export NODE_OPTIONS="--max-old-space-size=512 --openssl-legacy-provider"
      export GENERATE_SOURCEMAP=false
      ./build.sh
    startCommand: cd frontend && npx serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: REACT_APP_API_URL
        value: https://hatchling-backend.onrender.com
      - key: REACT_APP_API_BASE_URL
        value: https://hatchling-backend.onrender.com
      - key: REACT_APP_SOCKET_URL
        value: https://hatchling-backend.onrender.com
