version: '2'
services:
  # Backend service
  backend:
    name: hatchling-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://hatchling-frontend.onrender.com
      - key: USERS_FILE
        value: /data/users.json
      - key: DATA_DIR
        value: /data
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

  # Frontend service
  frontend:
    name: hatchling-frontend
    env: node
    buildCommand: |
      cd frontend
      export NODE_OPTIONS=--openssl-legacy-provider
      npm ci
      npm run build
    startCommand: cd frontend && npx serve -s build -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: REACT_APP_API_URL
        value: https://hatchling-backend.onrender.com
      - key: REACT_APP_API_BASE_URL
        value: https://hatchling-backend.onrender.com
      - key: REACT_APP_SOCKET_URL
        value: https://hatchling-backend.onrender.com
